name: anima
description: A minimalist e-ink book reader with GitHub cloud sync.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdf: ^25.1.37
  epubx: ^4.0.0
  pdfx: ^2.9.2
  archive: ^3.6.1
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
